language: node_js
node_js:
- node
cache:
  directories:
    - "node_modules"
script: npm run build
deploy:
  provider: npm
  email: marvin@luchs.org
  api_key:
    secure: B5ASuwfNHe3MdNUlU3DF+msOj8EKxCYlW6M6KUbMzRJ+5uxBEXhPfdYcI6wq7R2hQKOS+O5hPa5Ks7HkHmgiB9yrSTi36dWwQg/RyD6b2UmMsW4LNErgB0uiKmpC8uz+QKuapCFhDzKeRNZEgl6d1vC6dDVAK/2VcpDqjb7ag4ZTzAfnaYqdEjEUhV3T0KNuBQZcUYPpc4pK9qYue2i2N5/jlZrtL/h9aMqEy4+9vtKjCVkY75i0yJ/Zd2XLs7NZJaQRgQWbibmowHuyO6/qY69L93M62j7JPNDP6g/i7sn/zZh3AepMHNY7oS3MRDVI39qMmhYNYK8pAi3TQi0KPMinBxxT/VMHXG6B9pdeJ6dI0KFq7eBjb44BPuDaqi4M7E6glKtmWOOjXuaUkmdYIKZVaiguo/c8qvkrTpTcJB0bH3qPif6txtIaMXWV0EzQIPH27x66DOmV7aujtaHk03/ChEO4xfBgLoosjsD9x8THEB46zA7agSKYUxcnUMVLAesoEzPj830uKqeNS0rCJY034QsNhX///SY1UTd/2pYiacjEsa2niV4ygXwWL2mVUc0uzM2mkYG9ypg+I/T1PoAMSnFDUHAmfS3Uym4+ODsVYL8g15fywtbKs8PxMqxIGR053HzKWeOA9/QWoHatYujHL2XdbiskSHdsrp+oB4g=
  on:
    tags: true
  skip_cleanup: true
