language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
script: npm run build
deploy:
  provider: npm
  email: marvin@luchs.org
  api_key:
    secure: CnguxTVt1sK3n4lg86Wnu6N5iVKUykccVB6lOhLc+fj9sRi5povO+7uV7eYrRc4nEih/pCMwTUU87LcqLr54gNK4v7C976xktUwfFRoF2Lah0vRO5s1zS6wReJpxB42jzte7DtIj+WbA9B2dYKwWfmlwUfL6zWsGVmn2wYXRoQkdGhfFi7xRwESj4n4/+Pv3JY2EkBVssBfsAylS+hAsogXlzUvZYNvZ5+cwgxu6OZFgEdDfiB8GHQaVz3OGX+9J9ClPSF8HG6Z7U3H9J1IrVvv/kGK9Wb/6JhSaZbeXTu9TpNFPaZHUOcTnUzUqzglC7xw2qzdDMAmHislNm/k5X+UOEzg7iRNnuXosDG2OnKkbGvb9eAsJdzMz/ux7h1im2Uy9YyZc+AkW+uVKWtuiKVjGLxewP7Gz2ZtEtfDi1uhqTO+gCv+CGfd/DhD2rgoap9xS/LyK/xmNa/E/GmQPU2LlyX097v9BHWqs1kcagMgVU67zveI/SuIPmjA/HxfIHgbFhgBxKrjwChE9gbjsXXMeJ67c+BFkT3sKFcnex/Rjyer0sH1rKhKuC8r4yyrpb18Gz8/uTV9G2DV+yaYcUnc3LLOwgz8Bk9h73PIzoE8fVFixJLhZlpP8Ux7QItXZarXhhkpdALrvckL/lvL962jg3B5WAt9dTO5myxAL58M=
  on:
    tags: true
    repo: ngxp/log
    skip_cleanup: true
