language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
script: npm run build
deploy:
  provider: npm
  email: marvin@luchs.org
  api_key:
    secure: q6vmo5TDSJ9Spi+iwqA+J4gYLRzO0nHGFsNHOOfeLlcq20pUaqmUmf0kQOzvc1P6Np1sM/J/5DE6+4AbfMILj4rNgttg10isyHiTZM7vE9dqWqYNdpcKknk+nfvDGxhskE3vAxcH3MMUIg/mP+K2ZunpgQOLQRf5zpbZlm0xgncjIhf30+gIOsoHnAVoimN+yGBv2jW0EXtYL2WkbE13AY6m1+PrY8TvFxKQn/1pk2auJX1KLflZ0iVcHaSM2Tre1zxaONOkg6dUmOKHpyWjgN6+kQ4bbuckN2pSRuSKOZkSWpEx7SUVG7uISFy0hsoDS+jumZCT5SxYkxcph/yWA9FdMusDK7xGpvRtZ7F24rQUNG6+dU6wY76ncH/6MzbKpPNHkfoIVL+CXeV31eoPnwem1zqTZ4WmD3TA3vAzvMJI/esWpJizGB23p/bg2vHxUShyL1ZuS6MaQ5coErpEyk6uoXDHM+dkXihD1r82sqh2mmiqFoUYBInUA0cBteYsXlABd2UY7gZ17QqT/t5TL9lTc4VuVFw5XwIxawaOyJllDT8Mbypm4ztjYS+YQ+sDWooZqFrey3DOx7oWex2wBCc4bNzQJyUOdJ2KDBbxIt4N0sMpV9iTVDQYi41DUuA3UnnLfG065B8YfHODn8n3CpsxTayVVpr//NlXFrLOS8A=
  on:
    tags: true
  skip_cleanup: true
