language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
script: npm run build
deploy:
  provider: npm
  email: marvin@luchs.org
  api_key:
    secure: qZL+GDyPxuU/o/7PWkeI6zwc5hItlZCVOB921p48beOXmwnU6gWNIuD3GAmocil0wQoedvd3lWSWu79z340MmyZ0rmtcSroq62VRG83m/ZJd9L7HcB6uz585UtdutMb/XFfPs9OI88M5pKozcmuxw64/qegiWXWx6jsktMhWu7mTvFTQM7ePOuKFZfL9nu1BeWMNmNRafZEqoIOUEwNcgA35+/vaO8TKXhPNRGSSc/qU/qQ3EAtaK2g741YkpxmDJr/8+Q05ZNzvcRFED2aKLgdYIgmy/nqrR/zdJre780OY5QzUVjYbE8p9feYpWJp3HDAjlTeAJBk1LdukXZv5XV1qB4+hjAZMA3nN6djEojjT8Zpdn2OiwgS935Jqkq0YwcYtK4hSyQsJfVUrDHAs5oYUodVKIgUgpd3ZcfEd0dj+24DgrCvTAjtK7ziwUI+ERScyF155oh/bIQijrLbFSmyFKqb/xo+0uL3hx+nIT04nUaoSQdfWx87Q4Qa4lGW2sRykbPLX6dCIr7UwU8oErHqhcSKo2stTrpJXd8yuOn2OOnrs3n40ahsBB0t3KeDujZ/4H4SQgAZLh64HMbjwSKWtEc6xwG/1yKkiU9HdnLyo84XwEQznPslH65Bx1drB3Aeu/a4p54VLEuFMwmb3Ku/90o6JqMuh31ZDce6Jc5Q=
  on:
    tags: true
  skip_cleanup: true
