language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
script: npm run build
deploy:
  provider: npm
  email: marvin@luchs.org
  api_key:
    secure: lMuec5tgFiIjdCVXeWg9BT9GiXc6ArFw409bfCL9CRi14MIF+UGML2A2jM7wyi+rZWm59pLoidiUSwHvwkrKHbJ5XDSLE+eJR3dqzpExU+K26h6YXcAx1eZx/NtnFaSsC8Yx2FuuPSfdQUHJ/ZYA1ry1IFo5krcpBhAH6I+Sr73lOcmUlZYXVDmX/NKLleqbHZMjiW2uE7f0B7xgoq+fWeQRlKkUDqQUclabM7KVMhgDvgsgFnJCOa7228MlOxwgZOJrh24Ctx1syId1mviio8IxJ7r1Kj8Fhog7W1we+8v281SW5K14gg2EJ2Ye16fwawjcqsvfBpa+WNF1vAdDf8qvD9rN9+9tESRDgj4e3TX+a97+vd7STlZroq+b3bGGx8BnE4S2Nb95Q2qp5uUvCMOI7fQAapOYTz38MMvBFI3GlofJ8Y5c020ibf02af74Q27GUCRvC9ryVEw0hkRakL0cK53zEyyARW3aKmnIlaNizisqxU2/2Wi6LPpXp7PgM6sMEfy4dUmt3RR+r6DHoJvMY/GAKiEaZxphGques9j8YFhOYME2BUL+4/3lnvdSsCkgbCcOp2NcWvNTOmS8/tSxsM9UbaQez+e3rL10UCnbkLl7A/1JJH81k9+a8lJM4I7+Hp18/83G6TtvbYUOCEu51XO8aR3xx7pfdnpir/g=
  on:
    tags: true
  skip_cleanup: true
