language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
script: npm run build
deploy:
  provider: npm
  email: marvin@luchs.org
  api_key:
    secure: j1CDs6dID7p2GMxz3tBERY1YGhybffZRh17FNLwDPdN2YfbD+q8OLo4TgBNBR4ANJc1B49PSTJ14Wd8tD8fiSCahWzR2AHVtcUKpYJhGBN2epEM4pbnU1yeqkuvNZqB4HRx9CviVpILHJeX5Y67yJSqTJ0cTkzdr+7vXIKjmqsNGBLXrvWFfo5Or60iHFAzH3zgRyn3N/RjADs9H63PEM8//WkYbd7c2SfOrh4C6FaM6pC3GPVTVaRJ/Nj1ymbsDMBG9iGgNWcZmuwHaIbqmiQeFM33/lbDGJlSEqgBmE9iNvw0FNW5PpXkGEAWhomSGxX2owsig5VwuUnCYd5AEBSgl5vyQzjZp/Hs4mOtfYVv+YgtRebVUTsNx6aZqBTtaDotqlm8SOtEsP57ee6O8nfH2e+75ebxn3zJV5fg7IgaWEwFWcLsfKsnvNk1WzRmHSaNBSYMf3YZAd+UPpCOSs/+IaC12Rd+ONj8Jk+NJwNtTG9kgoEOcq1/T82Tp9woL/p7WQa3CoonpL7Dx25OUbBmtPqEZWBNaQx4sTxR3OyNAL3huDmjuDiixab5V0e2SPRF3NTjdul/7QrfndLIk/8nVBKNFiS7s0GKP9RJbFoXSbyPNTQt2kJcAx4u30rN4jrRhZtBwMdJlL+9uj1zfvQiKW0fIyz/wDvQYKI/VdG4=
  on:
    tags: true
    repo: ngxp/log
    skip_cleanup: true
